config:
  enabled:
    type: checkbox
    required: false
    label: Do you want to activate TNT Express National
  mode_production:
    type: checkbox
    required: false
    label: Use the production mode ?
    help: If not checked the test mode will be used.
  account_number:
    type: text
    required: true
    label: Your myTNT Account Number
  username:
    type: text
    required: true
    label: Your myTNT username
  password:
    type: text
    required: true
    LABEL: Your myTNT password
  use_individual:
    type: checkbox
    required: false
    label: Use individual delivery
  use_enterprise:
    type: checkbox
    required: false
    label: Use enterprise delivery
  use_depot:
    type: checkbox
    required: false
    label: Use TNT depot delivery
  use_dropoffpoint:
    type: checkbox
    required: false
    label: Use drop off point delivery
  products_enabled:
    type: text
    required: true
    label: List of available products
  options_enabled:
    type: text
    required: true
    label: List of available options
  regular_pickup:
    type: checkbox
    required: false
    label: Regular pickup
  sender_name:
    type: text
    required: true
    label: Name
  sender_address1:
    type: text
    required: true
    label: Address 1
  sender_address2:
    type: text
    required: false
    label: Address 2
  sender_zip_code:
    type: text
    required: true
    label: Zip code
  sender_city:
    type: text
    required: true
    label: City
  contact_lastname:
    type: text
    required: true
    label: Contact last name
  contact_firstname:
    type: text
    required: true
    label: Contact first name
  contact_email:
    type: text
    required: true
    label: Contact email
  contact_phone:
    type: text
    required: true
    label: Contact phone number
  notification_emails:
    type: text
    required: true
    label: Notification emails
    help: List of emails (separated by a ,) that will be notified on pick up anomaly.
  notification_success:
    type: checkbox
    required: false
    label: Notification on successful pick up
  label_format:
    type: text
    required: true
    label: Print format, options
  free_shipping:
    type: checkbox
    required: false
    label: Use free shipping
  max_weight_package:
    type: text
    required: false
    label: Max weight per package (kg)
  tracking_url:
    type: text
    required: false
    label: Parcel tracking URL
    help: %tracking-number% will be replaced by the parcel tracking number.
