config:
  enabled:
    type: checkbox
    label: Do you want to activate TNT Express National
  mode_production:
    type: checkbox
    label: Use the production mode ?
    help: if not checked the test mode will be used
  account_number:
    type: text
    required: true
    label: Your myTNT Account Number
  username:
    type: text
    required: true
    label: Your myTNT username
  password:
    type: text
    required: true
    LABEL: Your myTNT password
  use_individual:
    type: checkbox
    label: Use individual
  use_enterprise:
    type: checkbox
    label: Use enterprise
  use_depot:
    type: checkbox
    label: Use TNT depot
  use_dropoffpoint:
    type: checkbox
    label: Use drop off point
  products_enabled:
    type: text
    label: List of available products
  options_enabled:
    type: text
    label: List of available options
  regular_pickup:
    type: checkbox
    label: Regular pickup
  sender_name:
    type: text
    label: name
  sender_address1:
    type: text
    label: address 1
  sender_address2:
    type: text
    label: address 2
  sender_zip_code:
    type: text
    label: zip code
  sender_city:
    type: text
    label: City
  contact_lastname:
    type: text
    label: Contact last name
  contact_firstname:
    type: text
    label: Contact first name
  contact_email:
    type: text
    label: Contact email
  contact_phone:
    type: text
    label: Contact phone number
  notification_emails:
    type: text
    label: Notification emails
    help: List of emails (separated by a ,) that will be notified on pick up anomaly
  notification_success:
    type: checkbox
    label: Notification on successfull pick up
  label_format:
    type: text
    label: Print format, options
  free_shipping:
    type: checkbox
    label: Use free shipping
  max_weight_package:
    type: text
    label: Max weight per package (kg)
  tracking_url:
    type: text
    label: The tracking URL
    help: The URL to access to a parcel’s delivery status
